### PR TITLE
Reflect AST changes in Python 3.8.

### PR DESCRIPTION
**Pull request by serhiy-storchaka**
There will be several changes in AST in Python 3.8.

* `ast.Num`, `ast.Str`, `ast.Bytes`, `ast.Ellipsis` and `ast.NameConstant` are replaced with `ast.Constant`.
  (https://bugs.python.org/issue32892)

  `ast.Constant` can be used since Python 3.6, it is just that `ast.parse()` didn't produce it.

* Simplified AST for subscriptions. `ast.Index` is replaced with its value, `ast.ExtSlice` is replaced with `ast.Tuple`.
  (https://bugs.python.org/issue34822)

  *This change is not merged yet.*

### CODE REVIEW

**Comment by serhiy-storchaka** [comment]
This is a fix for #31.

**Comment by stonebig** [comment]
no merge ?

**Comment by almarklein** [comment]
Python 3.8 is not released yet, and I've had to undo changed before, for things that were changed in alpha/beta, but removed in the final release. I'd rather wait until there is a final release (or an rc).

**Comment by stonebig** [comment]
Also, it's hard to contest a change/make it improved  if nobody test it before rc.

**Comment by icarito** [comment]
I've tested the proposed change and can confirm that pscript works with Python 3.8 with this patch. I tested by directly deploying the `commonast.py` file to my installed pscript copy.

**Comment by almarklein** [comment]
Ok, let's do this :)

**Comment by almarklein** [comment]
also did a new release.

**Comment by almarklein** [comment]
I tweaked this some more in #39. And re-released (0.7.3)

**Pull request merged**
